matrix =input('Please enter four numbers seperated by spaces: ')
matrix_list = matrix.split(' ')
a1 = float(matrix_list[0])
b1 = float(matrix_list[1])
c1 = float(matrix_list[2])
d1 = float(matrix_list[3])
row_1_1 = (a1, b1)
row_2_1 = (c1, d1)
matrix_1 = (row_1_1, row_2_1)
print('matrix:',matrix_1)
inverse = 1 / (a1 * d1 - b1 * c1)
a2 = round(d1 * inverse, 1)
b2 = round(-b1 * inverse, 1)
c2 = round(-c1 * inverse, 1)
d2 = round(a1 * inverse, 1)
row_1_2 = (a2, b2)
row_2_2 = (c2, d2)
matrix_2 = (row_1_2, row_2_2)
print('inverse:',matrix_2)